// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDomain(arg1:string):Promise<boolean>;

export function DeleteDomain(arg1:string):Promise<boolean>;

export function GetBlockedDomains():Promise<Array<string>>;

export function Query(arg1:string):Promise<Array<string>>;
