// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDomain(arg1) {
  return window['go']['main']['App']['AddDomain'](arg1);
}

export function DeleteDomain(arg1) {
  return window['go']['main']['App']['DeleteDomain'](arg1);
}

export function GetBlockedDomains() {
  return window['go']['main']['App']['GetBlockedDomains']();
}

export function Query(arg1) {
  return window['go']['main']['App']['Query'](arg1);
}
